---
- name: Ensure git is installed (RedHat).
  package:
    name: "{{ git_packages }}"
    state: present
    enablerepo: "{{ git_enablerepo | default(omit, true) }}"
  when:
    - not git_install_from_source | bool
    - ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure git is installed (Debian).
  apt:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source | bool
    - ansible_os_family == 'Debian'

- name: Update pacman cache (Archlinux)
  pacman:
    update_cache: yes
  when: ansible_distribution == 'Archlinux'

- name: Ensure git is installed (Archlinux)
  pacman:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source | bool
    - ansible_distribution == 'Archlinux'

- name: Set Git global configuration
  become: false
  block:
    - name: Set git user.name
      command: git config --global user.name "{{ git_global_config.user_name }}"
    - name: Set git user.email
      command: git config --global user.email "{{ git_global_config.user_email }}"
  when: enable_git_global_config

- import_tasks: install-from-source.yml
  when: git_install_from_source | bool
